Rutorrent:
  ports:
  - ${PUBLIC_PORT}:80/tcp
  log_driver: ''
  labels:
    io.rancher.container.pull_image: always
  tty: true
  log_opt: {}
  image: linuxserver/rutorrent:latest
  volumes:
  - ${RUTORRENT_DATA_DIR}:/config
  - ${DOWNLOADS_DIR}:/downloads
  stdin_open: true
