Rutorrent:
  ports:
  - ${PUBLIC_PORT}:80/tcp
  - 9527:9527/udp
  - 5000:5000/tcp
  - 45566:45566/tcp
  - 45568:45568/tcp
  - 45569:45569/tcp
  - 45570:45570/tcp
  - 45571:45571/tcp
  - 45572:45572/tcp
  - 45573:45573/tcp
  - 45574:45574/tcp
  - 45575:45575/tcp
  - 45576:45576/tcp
  - 51413:51413/tcp
  environment:
  - PGID=999
  - PUID=1000
  log_driver: ''
  labels:
    io.rancher.container.pull_image: always
  tty: true
  log_opt: {}
  image: linuxserver/rutorrent
  volumes:
  - ${RUTORRENT_DATA_DIR}:/config
  - ${DOWNLOADS_DIR}:/downloads
  stdin_open: true
