Deluge:
  ports:
  - 53160:53160/tcp
  - 53160:53160/udp
  - ${PUBLIC_PORT}:8112/tcp
  - 58846:58846/tcp
  log_driver: ''
  labels:
    io.rancher.container.pull_image: always
  tty: true
  log_opt: {}
  image: bradshawit/deluge:latest
  volumes:
  - ${DELUGE_DATA_DIR}:/data/deluge
  - ${DOWNLOADS_DIR}:/data/downloads
  stdin_open: true
