.catalog:
  name: "Deluge"
  version: "v0.8"
  description: "Deluge torrent client"
  questions:
    - variable: public_port
      description: "public port to access the blog"
      label: "Public Port"
      required: true
      default: "80"
      type: "int"
ghost:
