Sickrage:
  ports:
  - ${PUBLIC_PORT}:8081/tcp
  log_driver: ''
  labels:
    io.rancher.container.pull_image: always
  tty: true
  log_opt: {}
  image: bradshawit/sickrage:latest
  volumes:
  - ${SICKRAGE_DATA_DIR}:/data/sickrage
  - ${TV_DIR}:/data/tv
  - ${DOWNLOADS_DIR}:/data/downloads
  - /etc/localtime:/etc/localtime:ro
  stdin_open: true
  volume_driver: convoy
