Sonarr:
  ports:
  - ${PUBLIC_PORT}:8989/tcp
  log_driver: ''
  labels:
    io.rancher.container.pull_image: always
  tty: true
  log_opt: {}
  image: bradshawit/docker-sonarr:latest
  volumes:
  - ${SONARR_DATA_DIR}:/data/sonarr
  - ${TV_DIR}:/data/tv
  - ${DOWNLOADS_DIR}:/data/downloads
  - ${TORRENT_DIR}:/data/torrentfiles
  stdin_open: true
